export const countryCurrencyMap = {
  Ghana: 'GHS',
  Nigeria: 'NGN',
  Kenya: 'KES',
  USA: 'USD',
  UK: 'GBP',
  Canada: 'CAD',
  India: 'INR',
  'South Africa': 'ZAR',
  Australia: 'AUD',
  Germany: 'EUR',
  France: 'EUR',
  Spain: 'EUR',
  Italy: 'EUR',
  Netherlands: 'EUR',
  Brazil: 'BRL',
  Mexico: 'MXN',
  Japan: 'JPY',
  China: 'CNY',
  'South Korea': 'KRW',
  Singapore: 'SGD',
  'New Zealand': 'NZD',
  Switzerland: 'CHF',
  Sweden: 'SEK',
  Norway: 'NOK',
  Denmark: 'DKK',
  Poland: 'PLN',
  'Czech Republic': 'CZK',
  Hungary: 'HUF',
  Romania: 'RON',
  Bulgaria: 'BGN',
  Croatia: 'HRK',
  Turkey: 'TRY',
  'United Arab Emirates': 'AED',
  'Saudi Arabia': 'SAR',
  Egypt: 'EGP',
  Morocco: 'MAD',
  Tunisia: 'TND',
  Algeria: 'DZD',
  Ethiopia: 'ETB',
  Tanzania: 'TZS',
  Uganda: 'UGX',
  Rwanda: 'RWF',
  Zambia: 'ZMW',
  Botswana: 'BWP',
  Namibia: 'NAD',
  Mauritius: 'MUR',
  Seychelles: 'SCR',
  Madagascar: 'MGA',
  'Ivory Coast': 'XOF',
  Senegal: 'XOF',
  Mali: 'XOF',
  'Burkina Faso': 'XOF',
  Niger: 'XOF',
  Benin: 'XOF',
  Togo: 'XOF',
  'Guinea-Bissau': 'XOF',
  Cameroon: 'XAF',
  'Central African Republic': 'XAF',
  Chad: 'XAF',
  'Republic of the Congo': 'XAF',
  'Equatorial Guinea': 'XAF',
  Gabon: 'XAF',
  Argentina: 'ARS',
  Chile: 'CLP',
  Colombia: 'COP',
  Peru: 'PEN',
  Uruguay: 'UYU',
  Paraguay: 'PYG',
  Bolivia: 'BOB',
  Ecuador: 'USD',
  Venezuela: 'VES',
  'Costa Rica': 'CRC',
  Panama: 'PAB',
  Guatemala: 'GTQ',
  Honduras: 'HNL',
  'El Salvador': 'USD',
  Nicaragua: 'NIO',
  'Dominican Republic': 'DOP',
  Jamaica: 'JMD',
  'Trinidad and Tobago': 'TTD',
  Barbados: 'BBD',
  Bahamas: 'BSD',
  'Puerto Rico': 'USD',
  Cuba: 'CUP',
  Haiti: 'HTG',
  Guyana: 'GYD',
  Suriname: 'SRD',
  'French Guiana': 'EUR',
  Belize: 'BZD',
  Thailand: 'THB',
  Vietnam: 'VND',
  Malaysia: 'MYR',
  Indonesia: 'IDR',
  Philippines: 'PHP',
  'Sri Lanka': 'LKR',
  Bangladesh: 'BDT',
  Pakistan: 'PKR',
  Afghanistan: 'AFN',
  Nepal: 'NPR',
  Bhutan: 'BTN',
  Maldives: 'MVR',
  Myanmar: 'MMK',
  Cambodia: 'KHR',
  Laos: 'LAK',
  Mongolia: 'MNT',
  'North Korea': 'KPW',
  Taiwan: 'TWD',
  'Hong Kong': 'HKD',
  Macau: 'MOP',
  Brunei: 'BND',
  'East Timor': 'USD',
  'Papua New Guinea': 'PGK',
  Fiji: 'FJD',
  'Solomon Islands': 'SBD',
  Vanuatu: 'VUV',
  'New Caledonia': 'XPF',
  'French Polynesia': 'XPF',
  Samoa: 'WST',
  Tonga: 'TOP',
  Kiribati: 'AUD',
  Tuvalu: 'AUD',
  Nauru: 'AUD',
  Palau: 'USD',
  'Marshall Islands': 'USD',
  'Federated States of Micronesia': 'USD',
  Russia: 'RUB',
  Ukraine: 'UAH',
  Belarus: 'BYN',
  Moldova: 'MDL',
  Georgia: 'GEL',
  Armenia: 'AMD',
  Azerbaijan: 'AZN',
  Kazakhstan: 'KZT',
  Kyrgyzstan: 'KGS',
  Tajikistan: 'TJS',
  Turkmenistan: 'TMT',
  Uzbekistan: 'UZS',
  Lithuania: 'EUR',
  Latvia: 'EUR',
  Estonia: 'EUR',
  Finland: 'EUR',
  Iceland: 'ISK',
  Ireland: 'EUR',
  Malta: 'EUR',
  Cyprus: 'EUR',
  Luxembourg: 'EUR',
  Belgium: 'EUR',
  Austria: 'EUR',
  Slovenia: 'EUR',
  Slovakia: 'EUR',
  Portugal: 'EUR',
  Greece: 'EUR',
  'North Macedonia': 'MKD',
  Albania: 'ALL',
  Montenegro: 'EUR',
  'Bosnia and Herzegovina': 'BAM',
  Serbia: 'RSD',
  Kosovo: 'EUR',
  Israel: 'ILS',
  Palestine: 'ILS',
  Jordan: 'JOD',
  Lebanon: 'LBP',
  Syria: 'SYP',
  Iraq: 'IQD',
  Iran: 'IRR',
  Kuwait: 'KWD',
  Bahrain: 'BHD',
  Qatar: 'QAR',
  Oman: 'OMR',
  Yemen: 'YER'
};

export const getCountryList = () => {
  return Object.keys(countryCurrencyMap).sort();
};

export const getCurrencyForCountry = (country) => {
  return countryCurrencyMap[country] || 'USD';
};

